package multiplayerquizapplication;
/**
 *
 * @author Sabit
 */

import java.util.*;
import javax.swing.JTextField;
import static multiplayerquizapplication.MultiplayerQuizApplication.playerRead;


public class RankPage extends javax.swing.JFrame {

    private Player[] players;

    public RankPage() {
        initComponents();
    
         Player[] players = playerRead("player.txt");
        if (players != null) {
      
            Player[] playersToRank = new Player[MultiplayerQuizApplication.getPlayerIndex()];
            int index = 0;
            for (int i = 0; i < players.length; i++) {
                if (players[i] != null) {
                    playersToRank[index++] = players[i];
                }
            }

            
            Arrays.sort(playersToRank, Comparator.comparingInt(Player::getNumOfWin).reversed());

            JTextField[] rankFields = {Rank1, Rank2, Rank3, Rank4, Rank5, Rank6, Rank7, Rank8, Rank9, Rank10};

            
            for (int i = 0; i < Math.min(playersToRank.length, rankFields.length); i++) {
                JTextField rankField = rankFields[i];
                Player player = playersToRank[i];
                rankField.setText((i + 1) + ". " + player.getName() + " - Wins: " + player.getNumOfWin());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Rank1 = new javax.swing.JTextField();
        Rank2 = new javax.swing.JTextField();
        Rank4 = new javax.swing.JTextField();
        Rank3 = new javax.swing.JTextField();
        Rank5 = new javax.swing.JTextField();
        Rank6 = new javax.swing.JTextField();
        Rank8 = new javax.swing.JTextField();
        Rank7 = new javax.swing.JTextField();
        Rank9 = new javax.swing.JTextField();
        Rank10 = new javax.swing.JTextField();
        ExitButton = new javax.swing.JButton();
        LoginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 100));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 820));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("                                     Ranking");

        Rank1.setEditable(false);
        Rank1.setBackground(new java.awt.Color(255, 255, 255));
        Rank1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Rank1.setForeground(new java.awt.Color(0, 0, 0));
        Rank1.setBorder(null);
        Rank1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rank1ActionPerformed(evt);
            }
        });

        Rank2.setEditable(false);
        Rank2.setBackground(new java.awt.Color(255, 255, 255));
        Rank2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Rank2.setForeground(new java.awt.Color(0, 0, 0));
        Rank2.setBorder(null);

        Rank4.setEditable(false);
        Rank4.setBackground(new java.awt.Color(255, 255, 255));
        Rank4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Rank4.setForeground(new java.awt.Color(0, 0, 0));
        Rank4.setBorder(null);

        Rank3.setEditable(false);
        Rank3.setBackground(new java.awt.Color(255, 255, 255));
        Rank3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Rank3.setForeground(new java.awt.Color(0, 0, 0));
        Rank3.setBorder(null);

        Rank5.setEditable(false);
        Rank5.setBackground(new java.awt.Color(255, 255, 255));
        Rank5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Rank5.setForeground(new java.awt.Color(0, 0, 0));
        Rank5.setBorder(null);

        Rank6.setEditable(false);
        Rank6.setBackground(new java.awt.Color(255, 255, 255));
        Rank6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Rank6.setForeground(new java.awt.Color(0, 0, 0));
        Rank6.setBorder(null);

        Rank8.setEditable(false);
        Rank8.setBackground(new java.awt.Color(255, 255, 255));
        Rank8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Rank8.setForeground(new java.awt.Color(0, 0, 0));
        Rank8.setBorder(null);

        Rank7.setEditable(false);
        Rank7.setBackground(new java.awt.Color(255, 255, 255));
        Rank7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Rank7.setForeground(new java.awt.Color(0, 0, 0));
        Rank7.setBorder(null);

        Rank9.setEditable(false);
        Rank9.setBackground(new java.awt.Color(255, 255, 255));
        Rank9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Rank9.setForeground(new java.awt.Color(0, 0, 0));
        Rank9.setBorder(null);

        Rank10.setEditable(false);
        Rank10.setBackground(new java.awt.Color(255, 255, 255));
        Rank10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Rank10.setForeground(new java.awt.Color(0, 0, 0));
        Rank10.setBorder(null);

        ExitButton.setBackground(new java.awt.Color(51, 51, 51));
        ExitButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(255, 255, 255));
        ExitButton.setText("Exit Game");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        LoginButton.setBackground(new java.awt.Color(51, 51, 51));
        LoginButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("Back To Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Rank3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rank1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rank2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rank4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rank5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rank6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rank7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rank8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rank9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rank10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(142, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(ExitButton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(790, Short.MAX_VALUE)
                    .addComponent(LoginButton)
                    .addGap(174, 174, 174)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Rank1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Rank2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Rank3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(Rank4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(Rank5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(Rank6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Rank7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(Rank8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Rank9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Rank10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(ExitButton)
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(774, Short.MAX_VALUE)
                    .addComponent(LoginButton)
                    .addGap(19, 19, 19)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        LoginPage loginpage = new LoginPage();
        loginpage.show();
        dispose();
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        ExitPage exitpage = new ExitPage();
        exitpage.show();
        dispose();
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void Rank1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rank1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rank1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RankPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RankPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RankPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RankPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RankPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton LoginButton;
    private javax.swing.JTextField Rank1;
    private javax.swing.JTextField Rank10;
    private javax.swing.JTextField Rank2;
    private javax.swing.JTextField Rank3;
    private javax.swing.JTextField Rank4;
    private javax.swing.JTextField Rank5;
    private javax.swing.JTextField Rank6;
    private javax.swing.JTextField Rank7;
    private javax.swing.JTextField Rank8;
    private javax.swing.JTextField Rank9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
